# Generated by Django 3.2.5 on 2021-08-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='meet',
            name='address',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meet',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='meet',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
