# Generated by Django 3.2.5 on 2021-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210809_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='address',
        ),
        migrations.AddField(
            model_name='meet',
            name='area1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meet',
            name='area2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meet',
            name='area3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
