# Generated by Django 3.2.5 on 2021-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userfriend_userrecent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
            ],
        ),
    ]
