# Generated by Django 3.2.5 on 2021-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userplayde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='kor_name',
        ),
        migrations.AddField(
            model_name='game',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
