# Generated by Django 3.2.5 on 2021-08-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210814_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meet',
        ),
    ]
