# Generated by Django 3.2.5 on 2021-08-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comment_community_communitylike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='community_id',
            new_name='board_id',
        ),
        migrations.RenameField(
            model_name='communitylike',
            old_name='community_id',
            new_name='board_id',
        ),
    ]
