# Generated by Django 3.2.5 on 2021-08-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210816_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('created_ad', models.DateTimeField(auto_now=True)),
                ('comment_id', models.IntegerField()),
            ],
        ),
    ]
