# Generated by Django 3.2.5 on 2021-08-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_commentreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
