# Generated by Django 3.2.5 on 2021-08-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_created_ad_commentreply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
